### PR TITLE
Initial import of full JSP text

### PR DESCRIPTION
**Pull request by markt-asf**
Before importing the full text, I aligned the JSP spec directory with EL and WebSocket. That cleaned up various bits and pieces.

The actual import of the full text is one asciidoc file and a bunch of images.

There is going to be a lot of clean-up to do once this PR is merged. It should be possible to use search/replace for most of it but experience from EL and WebSocket suggests we'll need a couple of proof-read & manual passes as well.

### CODE REVIEW

**Comment by arjantijms** [comment]
For Jakarta Authorization I had divided the single document into separate files per chapter, which may make maintenance and concurrent editing easier.

See https://github.com/eclipse-ee4j/jacc/tree/master/spec/src/main/asciidoc

Maybe that's something we want to do here as well?

**Comment by markt-asf** [comment]
From my experience with EL and WebSocket having it as a single doc will be easier for the initial conversion as there are so many global search and replace operations. After that, I'm currently neutral on breaking it up.

**Comment by arjantijms** [comment]
Using Eclipse for search and replace it typically doesn’t matter whether it’s one or more files ;)

**Comment by pnicolucci** [comment]
@markt-asf  sorry I had my comments in pending state, my mistake. Anyhow my comments are above for potential changes moving forward.

**Comment by markt-asf** [comment]
No problem. I'm working through a first pass at fixing the imported doc. This is mostly fixing formatting broken during the import and some of the bigger changes discussed on the project-leads list (drop previous change log entries, no need to duplicate DTDs and schema). I hope to have a PR for this soon. I'll include these changes in that.

**Pull request merged**
