### PR TITLE
Fix Issue 57

### PR DESCRIPTION
**Pull request by markt-asf**
In addition to the changes to the specification document, I spotted something missing in the API.

### CODE REVIEW

**Comment by joakime** [comment]
Sorry, I don't know enough about this behavior to review this.

The "spotted something missing" is also a bit to vague for me to work from.

**Comment by markt-asf** [comment]
To expand on "spotted something missing" I noticed that the `ScopedAttributeELResolver` was looking up imported static classes but not imported static fields. I believe that is an oversight.

**Comment by markt-asf** [comment]
I have been viewing this issue as explicitly documenting something that was implicitly understood. However, I can see that not everyone will see this issue that way. An alternative approach would be to "WONTFIX" this PR and the associated issue and address this in Jakarta EE 10 under #44 which has some ideas around additional resolvers that I find appealing.

**Comment by markt-asf** [comment]
As per my previous comment I am closing this PR without applying it.

**Pull request closed without merging**
