### PR TITLE
correction for https://github.com/eclipse-ee4j/glassfish/issues/22552

### PR DESCRIPTION
**Pull request by micRo-wlY**
add correction for https://github.com/eclipse-ee4j/glassfish/issues/22552

### CODE REVIEW

**Comment by bshannon** [comment]
Why was TldScanner.java deleted?

**Comment by micRo-wlY** [comment]
Sorry, the previous TldScanner.java uploaded the wrong location, so deleted.
The current pull request is our revised code, please confirm.

**Comment by bshannon** [comment]
It looks like you replaced the file with a different version with a different license.
Please check the diff output and make sure the license is correct and there are
no gratuitous whitespace differences.

Thanks.

**Comment by micRo-wlY** [comment]
Sorry, we have now ensured that the license is correct and there are gratuitous whitespace differences.
Trouble you to confirm the correction.
Thanks.  :)

**Comment by micRo-wlY** [comment]
Tested according to the provided code, a new problem has occurred.
When accessing 2 apps at the same time, one opens and the other displays HTTP Status 500, zip file closed

Testing process:
1.Deploy test app1 and app2 and start cluster.
2.Set breakpoints
org.apache.jasper.runtime.TldScanner
```
    private void scanJar(JarURLConnection conn, List<String> tldNames,boolean isLocal) throws JasperException {
        ...                        
        try {
            jarFile = conn.getJarFile();★Set breakpoints here
            synchronized (jarFile) {
            ...
                    // Update the jar TLD cache
                    tldInfos = tldInfoA.toArray(new TldInfo[tldInfoA.size()]);
                    jarTldCacheLocal.put(resourcePath, tldInfos);★Set breakpoints here
            ...
```
3.access app1 and app2.
4.At this time, two threads stop at the breakpoint.
5.Release the breakpoint, one app opens, and the other app displays 500.

What appears on the 500 page:

```
HTTP Status 500 - Internal Server Error

type Exception report
messageInternal Server Error
descriptionThe server encountered an internal error that prevented it from fulfilling this request.
exception 
org.apache.jasper.JasperException: PWC6180: Unable to initialize TldScanner

root cause 
java.lang.IllegalStateException: zip file closed

note The full stack traces of the exception and its root causes are available in the GlassFish Server Open Source Edition 4.1.2 logs.

GlassFish Server Open Source Edition 4.1.2 
```

**Comment by bshannon** [comment]
What does the stack trace show in the log file?

**Comment by micRo-wlY** [comment]
Web page display content:
```
HTTP Status 500 - Internal Server Error

type Exception report
messageInternal Server Error
descriptionThe server encountered an internal error that prevented it from fulfilling this request.
exception 
org.apache.jasper.JasperException: PWC6180: Unable to initialize TldScanner

root cause 
java.lang.IllegalStateException: zip file closed

note The full stack traces of the exception and its root causes are available in the GlassFish Server Open Source Edition 4.1.2 logs.
```


the stack trace:
```
[2019-06-05T16:46:27.444+0800] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=51 _ThreadName=http-listener-1(2)] [timeMillis: 1559724387444] [levelValue: 900] [[
  StandardWrapperValve[jsp]: Servlet.service() for servlet jsp threw exception
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:634)
	at java.util.zip.ZipFile.getEntry(ZipFile.java:305)
	at java.util.jar.JarFile.getEntry(JarFile.java:226)
	at sun.net.www.protocol.jar.URLJarFile.getEntry(URLJarFile.java:128)
	at java.util.jar.JarFile.getJarEntry(JarFile.java:209)
	at org.apache.jasper.runtime.TldScanner.scanJar(TldScanner.java:450)
	at org.apache.jasper.runtime.TldScanner.scanJars(TldScanner.java:743)
	at org.apache.jasper.runtime.TldScanner.scanTlds(TldScanner.java:353)
	at org.apache.jasper.runtime.TldScanner.getLocation(TldScanner.java:286)
```
						
```
[2019-06-05T16:53:36.143+0800] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=56 _ThreadName=http-listener-1(2)] [timeMillis: 1559724816143] [levelValue: 900] [[
  StandardWrapperValve[jsp]: Servlet.service() for servlet jsp threw exception
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:634)
	at java.util.zip.ZipFile.getInputStream(ZipFile.java:347)
	at java.util.jar.JarFile.getInputStream(JarFile.java:409)
	at org.apache.jasper.runtime.TldScanner.scanJar(TldScanner.java:451)
	at org.apache.jasper.runtime.TldScanner.scanJars(TldScanner.java:743)
	at org.apache.jasper.runtime.TldScanner.scanTlds(TldScanner.java:353)
	at org.apache.jasper.runtime.TldScanner.getLocation(TldScanner.java:286)
```


Corresponding code:
```
                if (tldInfos == null) {
                    ArrayList<TldInfo> tldInfoA = new ArrayList<TldInfo>();                    
                    if (tldNames != null) {
                        for (String tldName : tldNames) {
                            JarEntry entry = jarFile.getJarEntry(tldName); ★line450
                            InputStream stream = jarFile.getInputStream(entry);  ★line451
                            tldInfoA.add(scanTld(resourcePath, tldName, stream));
                        }
```

**Comment by bshannon** [comment]
I'm slowly getting enough understanding of this code...  :-)

It looks like the two threads have their own local caches, even though they share the same jarFile.
That means they each have to populate their local caches by reading the jar file.  The best
approach would be if conn.getJarFile returned a different JarFile object each time, or if two
different JarURLConnection objects would never return the same JarFile object.  But unfortunately
that's not how it works.  Each thread needs exclusive access to the JarFile object and needs to
close it when it's done, so when one thread is done the other thread that's waiting needs to get
a new JarFile object that's open and exclusively for it.  That means we have to add a retry loop:

```
    private void scanJar(JarURLConnection conn, List<String> tldNames,
                         boolean isLocal)
            throws JasperException {

        TldInfo[] tldInfos = null;
        JarFile jarFile = null;
        String resourcePath = conn.getJarFileURL().toString();
        try {
            boolean gotExclusiveAccess = false;
            while (!gotExclusiveAccess) { // try until we get exclusive access

            jarFile = conn.getJarFile();
            synchronized (jarFile) {
                try {
                    // just check whether the jar file is still open
                    jarFile.getManifest();
                    gotExclusiveAccess = true;
                } catch (IllegalStateException ex) {
                    // it's not open, need to try again
                    continue;
                }
                tldInfos = jarTldCacheLocal.get(resourcePath);

                // Optimize for most common cases: jars known to NOT have tlds
                if (tldInfos != null && tldInfos.length == 0) {
                    try {
                        conn.getJarFile().close();
                    } catch (IOException ex) {
                        //ignored
                    }
                    return;
                }

                // scan the tld if the jar has not been cached.
                if (tldInfos == null) {
                    ArrayList<TldInfo> tldInfoA = new ArrayList<TldInfo>();

                    if (tldNames != null) {
                        for (String tldName : tldNames) {
                            JarEntry entry = jarFile.getJarEntry(tldName);
                            InputStream stream = jarFile.getInputStream(entry);
                            tldInfoA.add(scanTld(resourcePath, tldName, stream));
                        }
                    } else {
                        Enumeration<JarEntry> entries = jarFile.entries();
                        while (entries.hasMoreElements()) {
                            JarEntry entry = entries.nextElement();
                            String name = entry.getName();
                            if (!name.startsWith("META-INF/")) continue;
                            if (!name.endsWith(".tld")) continue;
                            InputStream stream = jarFile.getInputStream(entry);
                            tldInfoA.add(scanTld(resourcePath, name, stream));
                        }
                    }
                    // Update the jar TLD cache
                    tldInfos = tldInfoA.toArray(new TldInfo[tldInfoA.size()]);
                    jarTldCacheLocal.put(resourcePath, tldInfos);
                    if (!isLocal) {
                        // Also update the global cache;
                        jarTldCache.put(resourcePath, tldInfos);
                    }
                }
            }

            } // end of retry loop
        } catch (IOException ex) {
            if (resourcePath.startsWith(FILE_PROTOCOL) &&
                    !((new File(resourcePath)).exists())) {
                if (log.isLoggable(Level.WARNING)) {
                    log.log(Level.WARNING,
                        Localizer.getMessage("jsp.warn.nojar",
                                             resourcePath),
                        ex);
                }
            } else {
                throw new JasperException(
                    Localizer.getMessage("jsp.error.jar.io", resourcePath),
                    ex);
            }
        } finally {
            if (jarFile != null) {
                try {
                    jarFile.close();
                } catch (Throwable t) {
                    // ignore
                }
            }
        }

        // Iterate over tldinfos to add listeners or to map tldlocations
        for (TldInfo tldInfo: tldInfos) {
            if (scanListeners) {
                addListener(tldInfo, isLocal);
            }
            mapTldLocation(resourcePath, tldInfo, isLocal);
        }
    }
```

This would benefit from additional refactoring to move the inner part of the retry
loop into another method.  And perhaps there should be a limit on the number of retries
that are allowed, just to prevent an infinite loop in case something unexpected happens.
But try this version and see if it works better.

**Comment by micRo-wlY** [comment]
After testing, the code is modified to the one you provide, or it will happen that two apps are accessed at the same time, and one page has 500 problems.

The log of the problem is as follows:
```
[2019-06-12T17:31:06.703+0800] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=55 _ThreadName=http-listener-1(3)] [timeMillis: 1560331866703] [levelValue: 900] [[
StandardWrapperValve[jsp]: Servlet.service() for servlet jsp threw exception
java.lang.IllegalStateException: zip file closed
at java.util.zip.ZipFile.ensureOpen(ZipFile.java:669)
at java.util.zip.ZipFile.getEntry(ZipFile.java:309)
at java.util.jar.JarFile.getEntry(JarFile.java:240)
at sun.net.www.protocol.jar.URLJarFile.getEntry(URLJarFile.java:128)
at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
at org.apache.jasper.runtime.TldScanner.scanJar(TldScanner.java:445)
at org.apache.jasper.runtime.TldScanner.scanJars(TldScanner.java:731)
at org.apache.jasper.runtime.TldScanner.scanTlds(TldScanner.java:335)
at org.apache.jasper.runtime.TldScanner.getLocation(TldScanner.java:275)
```

Corresponding code:
```
// scan the tld if the jar has not been cached.
if (tldInfos == null) {
	ArrayList<TldInfo> tldInfoA = new ArrayList<TldInfo>();

	if (tldNames != null) {
		for (String tldName : tldNames) {
			JarEntry entry = jarFile.getJarEntry(tldName);  ★line445
			InputStream stream = jarFile.getInputStream(entry);
			tldInfoA.add(scanTld(resourcePath, tldName,stream));
		}
```

**Comment by micRo-wlY** [comment]
After testing, the code is modified to the one you provide, or it will happen that two apps are accessed at the same time, and one page has 500 problems.


The log of the problem is as follows:
```
[2019-06-12T17:31:06.703+0800] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=55 _ThreadName=http-listener-1(3)] [timeMillis: 1560331866703] [levelValue: 900] [[
StandardWrapperValve[jsp]: Servlet.service() for servlet jsp threw exception
java.lang.IllegalStateException: zip file closed
at java.util.zip.ZipFile.ensureOpen(ZipFile.java:669)
at java.util.zip.ZipFile.getEntry(ZipFile.java:309)
at java.util.jar.JarFile.getEntry(JarFile.java:240)
at sun.net.www.protocol.jar.URLJarFile.getEntry(URLJarFile.java:128)
at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
at org.apache.jasper.runtime.TldScanner.scanJar(TldScanner.java:445)
at org.apache.jasper.runtime.TldScanner.scanJars(TldScanner.java:731)
at org.apache.jasper.runtime.TldScanner.scanTlds(TldScanner.java:335)
at org.apache.jasper.runtime.TldScanner.getLocation(TldScanner.java:275)
```

Corresponding code:
```
// scan the tld if the jar has not been cached.
if (tldInfos == null) {
	ArrayList<TldInfo> tldInfoA = new ArrayList<TldInfo>();

	if (tldNames != null) {
		for (String tldName : tldNames) {
			JarEntry entry = jarFile.getJarEntry(tldName);    ★line445
			InputStream stream = jarFile.getInputStream(entry);
			tldInfoA.add(scanTld(resourcePath, tldName,stream));
		}
```

**Comment by bshannon** [comment]
Sigh.  It looks like the implementation of JarFile.getManifest caches the result and will
return the manifest even after the JarFile is closed, so it can't be used to detect whether
the JarFile is still open.

Change `jarFile.getManifest();` to `jarFile.size();` and see if that works.

**Comment by micRo-wlY** [comment]
After testing, Change jarFile.getManifest(); to jarFile.size().
There will still be a problem with a web page 500。

**Comment by bshannon** [comment]
Is there a stack trace?

Do you understand how I'm trying to solve the original problem?
Are you not able to debug these failures yourself?

**Comment by micRo-wlY** [comment]
The stack where the error occurred before is as follows:

```
[2019-07-05T10:34:44.288+0800] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=52 _ThreadName=http-listener-1(3)] [timeMillis: 1562294084288] [levelValue: 900] [[
  StandardWrapperValve[jsp]: Servlet.service() for servlet jsp threw exception
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
	at java.util.zip.ZipFile.getInputStream(ZipFile.java:366)
	at java.util.jar.JarFile.getInputStream(JarFile.java:447)
	at org.apache.jasper.runtime.TldScanner.scanJar(TldScanner.java:449)
	at org.apache.jasper.runtime.TldScanner.scanJars(TldScanner.java:740)
	at org.apache.jasper.runtime.TldScanner.scanTlds(TldScanner.java:353)
	at org.apache.jasper.runtime.TldScanner.getLocation(TldScanner.java:286)
```

When the second app is processed, the first app processing closes the jarFile and causes the problem.

In order to avoid this problem, now add a synchronization in the close,
The code has been uploaded, please confirm.

**Comment by micRo-wlY** [comment]
This new correction has been uploaded, and it has been a while, please help me to confirm it as soon as possible, thank you very much.:)

**Comment by bshannon** [comment]
Sorry, I'm busy with the Jakarta EE 8 release and haven't had time to get back to this.
I took a quick look and it looked like your latest change was not just a simple fix to my
version but a completely different version, so it will take more time for me to evaluate that.

**Comment by micRo-wlY** [comment]
Sorry，that's OK，but can you estimate a time that you can evaluate it. It will be important for me to know the time. And thanks again.

**Comment by bshannon** [comment]
I'm hoping to get back to this next week.

**Comment by bshannon** [comment]
I'm finally getting back to this...

I'm not quite sure why you're getting the exception with my code.  It looks like it's
getting an IOException, which causes it to exit the synchronized block, allowing
another thread to enter the synchronized block, and then the first thread closes
the jar file as part of its exception handling, causing the second thread to get the
IllegalStateException.  I suppose that's possible, but I don't know what's causing
the IOException to begin with.

I don't see how your version solves the problem because it's opening and closing
the jar file outside of the synchronized block, which can cause code inside the synchronized
block to fail.

Here's a new version of my code that moves the exception handling inside the synchronized
block.  Since there doesn't seem to be a clean way to get the JarFile object to synchronize on
without potentially having to close it if there's an error, I changed it to synchronize on the
resourcePath String object.  Hopefully that will solve the problem.  With this approach the
retry loop to get exclusive access to the object may not be necessary, since all access to
the object occurs inside the synchronized block.

```
    private void scanJar(JarURLConnection conn, List<String> tldNames,
                         boolean isLocal)
            throws JasperException {

        TldInfo[] tldInfos = null;
        JarFile jarFile = null;
        String resourcePath = conn.getJarFileURL().toString().intern();
	boolean gotExclusiveAccess = false;
	while (!gotExclusiveAccess) { // try until we get exclusive access

	synchronized (resourcePath) {
	    try {
		jarFile = conn.getJarFile();
	    	try {
		    // just check whether the jar file is still open
		    jarFile.size();
		    gotExclusiveAccess = true;
		} catch (IllegalStateException ex) {
		    // it's not open, need to try again
		    continue;
		}
                tldInfos = jarTldCacheLocal.get(resourcePath);

                // Optimize for most common cases: jars known to NOT have tlds
                if (tldInfos != null && tldInfos.length == 0) {
                    try {
                        conn.getJarFile().close();
                    } catch (IOException ex) {
                        //ignored
                    }
                    return;
                }

                // scan the tld if the jar has not been cached.
                if (tldInfos == null) {
                    ArrayList<TldInfo> tldInfoA = new ArrayList<TldInfo>();

                    if (tldNames != null) {
                        for (String tldName : tldNames) {
                            JarEntry entry = jarFile.getJarEntry(tldName);
                            InputStream stream = jarFile.getInputStream(entry);
                            tldInfoA.add(scanTld(resourcePath, tldName, stream));
                        }
                    } else {
                        Enumeration<JarEntry> entries = jarFile.entries();
                        while (entries.hasMoreElements()) {
                            JarEntry entry = entries.nextElement();
                            String name = entry.getName();
                            if (!name.startsWith("META-INF/")) continue;
                            if (!name.endsWith(".tld")) continue;
                            InputStream stream = jarFile.getInputStream(entry);
                            tldInfoA.add(scanTld(resourcePath, name, stream));
                        }
                    }
                    // Update the jar TLD cache
                    tldInfos = tldInfoA.toArray(new TldInfo[tldInfoA.size()]);
                    jarTldCacheLocal.put(resourcePath, tldInfos);
                    if (!isLocal) {
                        // Also update the global cache;
                        jarTldCache.put(resourcePath, tldInfos);
                    }
                }

	    } catch (IOException ex) {
		if (resourcePath.startsWith(FILE_PROTOCOL) &&
			!((new File(resourcePath)).exists())) {
		    if (log.isLoggable(Level.WARNING)) {
			log.log(Level.WARNING,
			    Localizer.getMessage("jsp.warn.nojar",
						 resourcePath),
			    ex);
		    }
		} else {
		    throw new JasperException(
			Localizer.getMessage("jsp.error.jar.io", resourcePath),
			ex);
		}
	    } finally {
		if (jarFile != null) {
		    try {
			jarFile.close();
		    } catch (Throwable t) {
			// ignore
		    }
		}
	    }
	}

	} // end of retry loop

        // Iterate over tldinfos to add listeners or to map tldlocations
        for (TldInfo tldInfo: tldInfos) {
            if (scanListeners) {
                addListener(tldInfo, isLocal);
            }
            mapTldLocation(resourcePath, tldInfo, isLocal);
        }
    }
```

**Comment by bshannon** [comment]
Looks like you didn't include the Signed-Off-By header and so the ECA check is failing.
Please use "git commit -s --amend" and then "git push -f".

**Comment by micRo-wlY** [comment]
Sorry, I am submitting a Pull Request on the webpage without going through the git command line.
Could you tell me what the webpage operations for "git commit -s --amend" and "git push -f" are?

**Comment by bshannon** [comment]
Sorry, I don't know how to do this from the web user interface.

You can probably add the "Signed-Off-By" text to the bottom of the comment you supply for the commit, but I don't know how to "amend" your existing commit to add that to the comment.  You
may need to start over and submit a new PR.

**Comment by bshannon** [comment]
Please just start over with a new pull request.  You've got 8 commits for this pull request and every one of those commits needs a Signed-Off-By header.  You're not going to be able to do that.

**Comment by micRo-wlY** [comment]
I start a new pull request in this address:
https://github.com/eclipse-ee4j/jsp-api/pull/124
Please go and have a look, thank you very much.

**Pull request closed without merging**
