### PR TITLE
Issue #152 - Renaming javax -> jakarta

### PR DESCRIPTION
**Pull request by joakime**
+ javax.servlet -> jakarta.servlet
+ javax.el -> jakarta.el

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

**Comment by joakime** [comment]
> There looked to be a little more than the name change in the PR. Was the existing code not Servlet 4.0 compliant?

There was some unused import statement cleanups as part of this too.

The biggest / oddest change was to `impl/src/main/java/org/apache/jasper/servlet/JspCServletContext.java`
See: https://github.com/eclipse-ee4j/jsp-api/pull/153/files#diff-139ef91b0200680af6c2e2b2d687c0f7

That class had the following signature ...

https://github.com/eclipse-ee4j/jsp-api/blob/29a02da7ead116278f31dcd3282a2240a9cc3922/impl/src/main/java/org/apache/jasper/servlet/JspCServletContext.java#L62

The `ServletContext` has many new methods that were introduced in Servlet 4.0.x.
This PR updated the `/impl/` from Servlet 3.0.1 to 5.0.0-M1

**Comment by joakime** [comment]
I found a ServletContainerInitializer I missed.
Update incoming shortly.

**Comment by joakime** [comment]
Also, the references to `/javax/servlet/.../*.dtd` are not updated in the `Constants.java`

https://github.com/eclipse-ee4j/jsp-api/blob/29a02da7ead116278f31dcd3282a2240a9cc3922/impl/src/main/java/org/apache/jasper/Constants.java#L153-L154

I felt like those should not be updated.
That make sense?

**Comment by markt-asf** [comment]
LGTM.
I probably would move the schema files to the new package but as long as the constants agree with the current location all is good.

**Comment by joakime** [comment]
The schema files mentioned in `Constants.java` are for Servlet 2.5 and older.

Those old specs are still `javax.servlet`, so moving them doesn't make sense.
Also, those schema files are not present in this repository.

**Comment by joakime** [comment]
Noone else has said anything, so I'll merge it.

**Pull request merged**
