### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by arjantijms**
Update parent to 1.0.5 and servlet dependency to Jakarta, some ordering and new lines added.

### CODE REVIEW

**Comment by anajosep** [comment]
The changes looks good to me. I don't have option to approve.

**Comment by arjantijms** [comment]
Ah, sorry Mark, you indeed mentioned this before and I just forgot about it. My bad! I'll change it back right away.

**Comment by arjantijms** [comment]
@markt-asf I changed the references back to javax. Can you take a look again?

**Comment by markt-asf** [comment]
For my education, why change the order? Convention? Validation? Something else?

**Comment by arjantijms** [comment]
@markt-asf The convention indeed, to align somewhat better with the other projects. 

See the recommended ordering here: https://maven.apache.org/developers/conventions/code.html

**Comment by markt-asf** [comment]
Tx.

**Pull request merged**
