### PR TITLE
Clean poms, formatting, versions and automatic module id

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by joakime** [comment]
We have a jsp-api 3.0.0 (final, non-rc, non-milestone) release already.

Wouldn't this be more appropriate for jsp-api 4.0.0, for Jakarta EE 10 effort?

**Comment by arjantijms** [comment]
> We have a jsp-api 3.0.0 (final, non-rc, non-milestone) release already.

Do we? I don't think we can release a final until the ballot has been completed.

**Comment by arjantijms** [comment]
> Wouldn't this be more appropriate for jsp-api 4.0.0, for Jakarta EE 10 effort?

Nope, this is definitely not API 4 level.

**Review by m0mus — APPROVED** [review]
LGTM

**Pull request merged**
