### PR TITLE
Parent POM updated to 1.0.6

### PR DESCRIPTION
**Pull request by Tomas-Kraus**
This is required before release rebuild.

### CODE REVIEW

**Comment by markt-asf** [comment]
I'd expect the release to be made from the EE4J branch (like 2.3.4 and 2.3.5 were).
Looking at the git history the 2.3.6 release was made from master which doesn't look right.
The 2.3.5 and 2.3.6 releases were made with zero references on the JSP mailing lists which makes me wonder how happened as I'd expect to see a release review on list. I really have no idea what is / has been going on with 2.3.x releases post the 2.3.4 release and therefore do not feel able to comment either in favour or against this PR.

**Comment by Tomas-Kraus** [comment]
2.3.6 release has it's own branch based on 2.3.6-RELEASE tag. It was in staging several months ago. I have no idea if it's standalone release from master or part of EE4J 8. I'm just rebuiulding exactly the same code that was lost.

**Comment by m0mus** [comment]
@markt-asf You are right. 2.3.5 release should've been done from `EE4J_8` branch, but API release was done from `master`. I also couldn't find any commit which merges changes in `EE4J_8` to `master`. Maybe there were double commits to `EE4J_8` and to `master'. 
Considering above, I think we should release `2.3.6` from `master` to staging only, make sure that all TCK tests are passing and release it to public only after that.
Also, someone have to make sure that `EE4J_8` branch is properly merged to `master` and delete it after that.

**Comment by m0mus** [comment]
If it had it's own branch it makes sense using it for 2.3.6 release. Again, we need to make sure that TCK tests are passing.

**Comment by Tomas-Kraus** [comment]
@m0mus So you would like to release it on the top of current master? I don't think it's a good idea because release tag is there for months and community can already have builds based on this tag.
That's why I just wanted to put exactly the same state to staging and central.
But if you guys want 2.3.6 on the top of master with some new EE4J8 merges, I'll do that.
I'll delete old release tag and we can go on.

**Comment by m0mus** [comment]
@Tomas-Kraus When I was writing about `master` I didn't know about the dedicated `2.3.6` branch. @markt-asf Are you fine to make a stanging release from `2.3.6` branch?

**Comment by Tomas-Kraus** [comment]
Think that proper solution is to release 2.3.6 from 2.3.6 branch because it still contains `javax.servlet` packages! 
And then make another release on the top of master with `jakarta.servlet` packages and other required updates - which is already being prepared as 3.0.0.

**Comment by markt-asf** [comment]
master has all the changes it needs and is getting ready for the 3.0.0 release.
I'm happy to defer to others as the right place to start a 2.3.6 implementation release. All I know for sure is that that place is not master.

**Pull request merged**
