### PR TITLE
3.0.0 branch merge

### PR DESCRIPTION
**Pull request by arjantijms**
Administrative merge to complete https://github.com/eclipse-ee4j/jsp-api/issues/195

### CODE REVIEW

**Comment by markt-asf** [comment]
These version numbers don't look right to me.
I think everything needs to move to 3.1.0-SNAPSHOT. If there is a need for a 3.0.x patch release then we can create an appropriate branch from the 3.0.0 tag.

**Comment by arjantijms** [comment]
This is just an administrative merge, feel free to overwrite the versions afterwards. It's just so that the 3.0.0 doesn't show the "2 commits ahead" message, which tools etc can check for.

**Comment by markt-asf** [comment]
I don't really see the point of this then - but neither is there really any harm. I'll merge this and then create a PR to set some realistic version numbers.

**Review by markt-asf — APPROVED** [review]

**Comment by arjantijms** [comment]
Thanks! It's a requirement for all Jakarta API projects, so if there's no point to it, it's perhaps best to address it at the platform level so it can be changed for all projects at the same time.

**Pull request merged**
